--DOES DELIVERED FG HAVE CALCULATION
--SELECT ITH_SER,SER_DOC FROM
--(select ITH_SER from v_ith_tblc where ITH_DATEC between '2021-09-26' and convert(date,getdate()) and ITH_WH='ARSHP' AND ITH_QTY<0 ) VBEFFG
--LEFT JOIN (SELECT DISTINCT SERD2_SER FROM SERD2_TBL ) VSERD2
--ON ITH_SER=SERD2_SER
--LEFT JOIN SER_TBL ON ITH_SER=SER_ID
--WHERE SERD2_SER IS NULL  AND SER_DOC NOT LIKE '%-C%'
--ORDER BY SER_DOC, ITH_SER

----IS DELIVERED FG CALCULATION OK
SELECT VRESUME_PER_JOB.*, TTLPERREQ FROM 
(SELECT SERD2_SER,JOB,SUM(PER) TTLPER FROM
(SELECT SERD2_SER,SERD2_ITMCD,SUM(SERD2_QTY)/MAX(SERD2_FGQTY) PER, MAX(SERD2_JOB) JOB FROM SERD2_TBL WHERE SERD2_SER IN (
select ITH_SER from v_ith_tblc where ITH_DATEC between '2021-09-26' and convert(date,getdate()) and ITH_WH='ARSHP' AND ITH_QTY<0 
)
GROUP BY SERD2_SER ,SERD2_ITMCD) VRESUME_PER_ITEM
GROUP BY SERD2_SER,JOB) VRESUME_PER_JOB
LEFT JOIN
(
SELECT PIS3_WONO,SUM(REQPER) TTLPERREQ FROM
	(SELECT PIS3_WONO,PIS3_MPART,SUM(PIS3_REQQT)/SIMQT REQPER FROM XPIS3 
		RIGHT JOIN ( SELECT PPSN1_WONO,MAX(PPSN1_SIMQT) SIMQT,PPSN1_DOCNO FROM XPPSN1 GROUP BY PPSN1_WONO,PPSN1_DOCNO) VRESUME_PSN1 ON PIS3_WONO=PPSN1_WONO AND PIS3_DOCNO=PPSN1_DOCNO
		WHERE PIS3_WONO IN (SELECT SER_DOC FROM
								(select ITH_SER from v_ith_tblc where ITH_DATEC between '2021-09-26' and convert(date,getdate()) and ITH_WH='ARSHP' AND ITH_QTY<0  ) VBEFFG
								LEFT JOIN SER_TBL ON ITH_SER=SER_ID
								WHERE isnull(SER_RMUSE_COMFG,'')!='flg_ok'
								GROUP BY SER_DOC
								) 
	GROUP BY PIS3_WONO
		,PIS3_MPART,SIMQT,PIS3_DOCNO
) VRESUME_PIS
GROUP BY PIS3_WONO) VRESUME_PISREQ_JOB ON JOB=PIS3_WONO
LEFT JOIN SER_TBL ON SERD2_SER=SER_ID
WHERE TTLPER<TTLPERREQ AND isnull(SER_RMUSE_COMFG,'')!='flg_ok' AND (TTLPERREQ-TTLPER) >=1
and (TTLPERREQ<>  TTLPER*2)
ORDER BY JOB