declare @wh varchar(20)
set @wh = 'AFWH9SC'
--IS HAS CALCULATION
--SELECT ITH_SER FROM
--(SELECT ITH_SER FROM v_ith_tblc WHERE  ITH_FORM NOT IN ('SASTART','SA') AND ITH_DATEC<'2021-05-01' 
--AND ITH_WH IN (@wh)
--GROUP BY ITH_WH,ITH_SER
--HAVING SUM(ITH_QTY)>0 ) VBEFFG
--LEFT JOIN (SELECT DISTINCT SERD2_SER FROM SERD2_TBL ) VSERD2
--ON ITH_SER=SERD2_SER
--WHERE SERD2_SER IS NULL 

----IS CALCULATION OK
--SELECT VRESUME_PER_JOB.*, TTLPERREQ FROM 
--(SELECT SERD2_SER,JOB,SUM(PER) TTLPER FROM
--(SELECT SERD2_SER,SERD2_ITMCD,SUM(SERD2_QTY)/MAX(SERD2_FGQTY) PER, MAX(SERD2_JOB) JOB FROM SERD2_TBL WHERE SERD2_SER IN (
--SELECT ITH_SER FROM v_ith_tblc WHERE  ITH_FORM NOT IN ('SASTART','SA') AND ITH_DATEC<='2021-05-01' 
--AND ITH_WH IN (@wh)
--GROUP BY ITH_WH,ITH_SER
--HAVING SUM(ITH_QTY)>0 
--)
--GROUP BY SERD2_SER ,SERD2_ITMCD) VRESUME_PER_ITEM
--GROUP BY SERD2_SER,JOB) VRESUME_PER_JOB
--LEFT JOIN
--(
--SELECT PIS3_WONO,SUM(REQPER) TTLPERREQ FROM
--	(SELECT PIS3_WONO,PIS3_MPART,SUM(PIS3_REQQT)/SIMQT REQPER FROM XPIS3 
--		RIGHT JOIN ( SELECT PPSN1_WONO,MAX(PPSN1_SIMQT) SIMQT,PPSN1_DOCNO FROM XPPSN1 GROUP BY PPSN1_WONO,PPSN1_DOCNO) VRESUME_PSN1 ON PIS3_WONO=PPSN1_WONO AND PIS3_DOCNO=PPSN1_DOCNO
--		WHERE PIS3_WONO IN (SELECT SER_DOC FROM
--								(SELECT ITH_SER FROM v_ith_tblc WHERE  ITH_FORM NOT IN ('SASTART','SA') AND ITH_DATEC<='2021-05-01' AND ITH_WH IN (@wh) GROUP BY ITH_SER
--									HAVING SUM(ITH_QTY)>0 ) VBEFFG
--		LEFT JOIN SER_TBL ON ITH_SER=SER_ID) 
--	GROUP BY PIS3_WONO
--		,PIS3_MPART,SIMQT,PIS3_DOCNO
--) VRESUME_PIS
--GROUP BY PIS3_WONO) VRESUME_PISREQ_JOB ON JOB=PIS3_WONO
--WHERE TTLPER<TTLPERREQ



--IS CALCULATION OK SUB ASSY
SELECT VRESUME_PER_JOB.*, TTLPERREQ FROM 
(SELECT SERD2_SER,JOB,SUM(PER) TTLPER FROM
(SELECT SERD2_SER,SERD2_ITMCD,SUM(SERD2_QTY)/MAX(SERD2_FGQTY) PER, MAX(SERD2_JOB) JOB FROM SERD2_TBL WHERE SERD2_SER IN (SELECT SERML_COMID FROM
(SELECT ITH_SER,SUM(ITH_QTY) BEFQTYFG, ITH_WH FROM v_ith_tblc WHERE  ITH_FORM NOT IN ('SASTART','SA') AND ITH_DATEC<'2021-05-01'
		AND ITH_WH IN ('AFWH3','QAFG','AFWH9SC','AWIP1','ARSHP')
		GROUP BY ITH_WH,ITH_SER
		HAVING SUM(ITH_QTY)>0) VBEFFG
INNER JOIN SERML_TBL ON ITH_SER= SERML_NEWID
)
GROUP BY SERD2_SER ,SERD2_ITMCD) VRESUME_PER_ITEM
GROUP BY SERD2_SER,JOB) VRESUME_PER_JOB
LEFT JOIN
(
SELECT PIS3_WONO,SUM(REQPER) TTLPERREQ FROM
	(SELECT PIS3_WONO,PIS3_MPART,SUM(PIS3_REQQT)/SIMQT REQPER FROM XPIS3 
		RIGHT JOIN ( SELECT PPSN1_WONO,MAX(PPSN1_SIMQT) SIMQT,PPSN1_DOCNO FROM XPPSN1 GROUP BY PPSN1_WONO,PPSN1_DOCNO) VRESUME_PSN1 ON PIS3_WONO=PPSN1_WONO AND PIS3_DOCNO=PPSN1_DOCNO
		WHERE PIS3_WONO IN (SELECT SER_DOC FROM
								(SELECT ITH_SER FROM v_ith_tblc WHERE  ITH_FORM NOT IN ('SASTART','SA') AND ITH_DATEC<'2021-05-01' AND ITH_WH IN (@wh) GROUP BY ITH_SER
									HAVING SUM(ITH_QTY)>0 ) VBEFFG
		LEFT JOIN SER_TBL ON ITH_SER=SER_ID) 
	GROUP BY PIS3_WONO
		,PIS3_MPART,SIMQT,PIS3_DOCNO
) VRESUME_PIS
GROUP BY PIS3_WONO) VRESUME_PISREQ_JOB ON JOB=PIS3_WONO
WHERE TTLPER<TTLPERREQ



---extra
---FG WH
---AFHW3, ARSHP, QAFG, AR
(SELECT VBEFFG.*,SER_ITMID,SER_DOC FROM
(SELECT ITH_SER,SUM(ITH_QTY) BEFQTYFG, ITH_WH FROM v_ith_tblc WHERE  ITH_FORM NOT IN ('SASTART','SA') AND ITH_DATEC<'2021-05-01' 
AND ITH_WH IN ('AWIP1')
GROUP BY ITH_WH,ITH_SER
HAVING SUM(ITH_QTY)>0) VBEFFG
LEFT JOIN (SELECT SERD2_SER FROM SERD2_TBL GROUP BY SERD2_SER) VSERD ON ITH_SER= VSERD.SERD2_SER
LEFT JOIN SER_TBL ON ITH_SER=SER_ID
WHERE SERD2_SER IS NULL)

SELECT ITH_SER,BEFQTYFG,ITH_WH,SER_DOC,  MAX(SERD2_SER_SMP) SERD2SER_SMP FROM
(SELECT VBEFFG.*,SER_ITMID,SER_DOC FROM
(SELECT ITH_SER,SUM(ITH_QTY) BEFQTYFG, ITH_WH FROM v_ith_tblc WHERE  ITH_FORM NOT IN ('SASTART','SA') AND ITH_DATEC<'2021-05-01' 
AND ITH_WH IN ('AFWH3')
GROUP BY ITH_WH,ITH_SER
HAVING SUM(ITH_QTY)>0) VBEFFG
LEFT JOIN (SELECT SERD2_SER FROM SERD2_TBL GROUP BY SERD2_SER) VSERD ON ITH_SER= VSERD.SERD2_SER
LEFT JOIN SER_TBL ON ITH_SER=SER_ID
WHERE SERD2_SER IS NULL) VH1
LEFT JOIN (SELECT SERD2_SER SERD2_SER_SMP, MAX(SERD2_JOB) SERD2JOB FROM SERD2_TBL GROUP BY SERD2_SER) VSERDSMP ON SER_DOC=SERD2JOB
GROUP BY  ITH_SER,BEFQTYFG,ITH_WH,SER_DOC





--SELECT DISTINCT SER_DOC FROM
--(SELECT ITH_SER, ITH_WH, SER_DOC FROM v_ith_tblc 
--LEFT JOIN SER_TBL ON ITH_SER=SER_ID
--WHERE 
--ITH_FORM NOT IN ('SASTART','SA') AND ITH_DATEC<'2021-05-01' 
--AND ITH_WH IN ('AFWH3')
--GROUP BY ITH_WH,ITH_SER,SER_DOC
--HAVING SUM(ITH_QTY)>0) VBEFFG2
--LEFT JOIN (SELECT SERD2_SER FROM SERD2_TBL GROUP BY SERD2_SER) VSERD ON ITH_SER= VSERD.SERD2_SER
--WHERE SERD2_SER IS NULL




--ALL RM FROM RM
SELECT * FROM
(SELECT ITH_ITMCD,SUM(ITH_QTY) BEFQTY,ITH_WH FROM v_ith_tblc a 
			WHERE ITH_WH IN ('ARWH2','NRWH2','PLANT1','PLANT2','ARWH0PD','PLANT_NA','ARWH9SC','QA')
			AND ITH_FORM NOT IN ('SASTART','SA') AND ITH_DATEC<'2021-05-01'
			GROUP BY ITH_ITMCD,ITH_WH) VBEF
ORDER BY ITH_ITMCD






select v1.*, SER_ITMID from
(select SERD2_ITMCD,CEILING(SUM(SERD2_QTY)*2)/2 RMQTY,SERD2_SER from SERD2_TBL left join MITM_TBL on SERD2_ITMCD=MITM_ITMCD WHERE MITM_MODEL='0' AND SERD2_SER IN 
        (SELECT ITH_SER FROM v_ith_tblc WHERE  ITH_FORM NOT IN ('SASTART','SA') AND ITH_DATEC<='2021-04-30'
		AND ITH_WH IN ('AFWH3','QAFG','AFWH9SC','AWIP1','ARSHP')
		GROUP BY ITH_WH,ITH_SER
		HAVING SUM(ITH_QTY)>0) GROUP BY SERD2_SER,SERD2_ITMCD) v1
		left join SER_TBL on SERD2_SER=SER_ID
where SERD2_ITMCD in
(
'E12071',
'218973600',
'211313600',
'208977800',
'213969800',
'216259100',
'216287000',
'210270400',
'214839400',
'212718900',
'2216926-7',
'214337300',
'216255300',
'201799500',
'212836500',
'208652400',
'203278100',
'206311400',
'212702000',
'210494200',
'216291400',
'202537400',
'217386400',
'211323000',
'217167500',
'211381800',
'212118300',
'209141200',
'217412500',
'215077203',
'215491500',
'212176200',
'214834300',
'209175400',
'212105100',
'215480801',
'202527200',
'209179300',
'203439400'
)




--DOES DELIVERED FG HAVE CALCULATION
SELECT ITH_SER,SER_DOC FROM
(select ITH_SER from v_ith_tblc where ITH_DATEC between '2021-09-06' and '2021-09-10' and ITH_WH='ARSHP' AND ITH_QTY<0 ) VBEFFG
LEFT JOIN (SELECT DISTINCT SERD2_SER FROM SERD2_TBL ) VSERD2
ON ITH_SER=SERD2_SER
LEFT JOIN SER_TBL ON ITH_SER=SER_ID
WHERE SERD2_SER IS NULL 
ORDER BY SER_DOC, ITH_SER

----IS DELIVERED FG CALCULATION OK
SELECT VRESUME_PER_JOB.*, TTLPERREQ FROM 
(SELECT SERD2_SER,JOB,SUM(PER) TTLPER FROM
(SELECT SERD2_SER,SERD2_ITMCD,SUM(SERD2_QTY)/MAX(SERD2_FGQTY) PER, MAX(SERD2_JOB) JOB FROM SERD2_TBL WHERE SERD2_SER IN (
select ITH_SER from v_ith_tblc where ITH_DATEC between '2021-09-06' and '2021-09-10' and ITH_WH='ARSHP' AND ITH_QTY<0 
)
GROUP BY SERD2_SER ,SERD2_ITMCD) VRESUME_PER_ITEM
GROUP BY SERD2_SER,JOB) VRESUME_PER_JOB
LEFT JOIN
(
SELECT PIS3_WONO,SUM(REQPER) TTLPERREQ FROM
	(SELECT PIS3_WONO,PIS3_MPART,SUM(PIS3_REQQT)/SIMQT REQPER FROM XPIS3 
		RIGHT JOIN ( SELECT PPSN1_WONO,MAX(PPSN1_SIMQT) SIMQT,PPSN1_DOCNO FROM XPPSN1 GROUP BY PPSN1_WONO,PPSN1_DOCNO) VRESUME_PSN1 ON PIS3_WONO=PPSN1_WONO AND PIS3_DOCNO=PPSN1_DOCNO
		WHERE PIS3_WONO IN (SELECT SER_DOC FROM
								(select ITH_SER from v_ith_tblc where ITH_DATEC between '2021-09-06' and '2021-09-10' and ITH_WH='ARSHP' AND ITH_QTY<0  ) VBEFFG
								LEFT JOIN SER_TBL ON ITH_SER=SER_ID
								WHERE isnull(SER_RMUSE_COMFG,'')!='flg_ok'
								GROUP BY SER_DOC
								) 
	GROUP BY PIS3_WONO
		,PIS3_MPART,SIMQT,PIS3_DOCNO
) VRESUME_PIS
GROUP BY PIS3_WONO) VRESUME_PISREQ_JOB ON JOB=PIS3_WONO
LEFT JOIN SER_TBL ON SERD2_SER=SER_ID
WHERE TTLPER<TTLPERREQ AND isnull(SER_RMUSE_COMFG,'')!='flg_ok' AND (TTLPERREQ-TTLPER) >=1
and (TTLPERREQ<>  TTLPER*2)
ORDER BY JOB


declare @wh varchar(20)
declare @cutoff varchar(10)
set @wh = 'AWIP1'
set @cutoff = '2021-07-31'
----IS CALCULATION OK
SELECT VRESUME_PER_JOB.*, TTLPERREQ FROM 
(SELECT SERD2_SER,JOB,SUM(PER) TTLPER FROM
(SELECT SERD2_SER,SERD2_ITMCD,SUM(SERD2_QTY)/MAX(SERD2_FGQTY) PER, MAX(SERD2_JOB) JOB FROM SERD2_TBL WHERE SERD2_SER IN (
SELECT ITH_SER FROM v_ith_tblc WHERE  ITH_FORM NOT IN ('SASTART','SA') AND ITH_DATEC<=@cutoff
AND ITH_WH IN (@wh)
GROUP BY ITH_WH,ITH_SER
HAVING SUM(ITH_QTY)>0 
)
GROUP BY SERD2_SER ,SERD2_ITMCD) VRESUME_PER_ITEM
GROUP BY SERD2_SER,JOB) VRESUME_PER_JOB
LEFT JOIN
(
SELECT PIS3_WONO,SUM(REQPER) TTLPERREQ FROM
	(SELECT PIS3_WONO,PIS3_MPART,SUM(PIS3_REQQT)/SIMQT REQPER FROM XPIS3 
		RIGHT JOIN ( SELECT PPSN1_WONO,MAX(PPSN1_SIMQT) SIMQT,PPSN1_DOCNO FROM XPPSN1 GROUP BY PPSN1_WONO,PPSN1_DOCNO) VRESUME_PSN1 ON PIS3_WONO=PPSN1_WONO AND PIS3_DOCNO=PPSN1_DOCNO
		WHERE PIS3_WONO IN (SELECT SER_DOC FROM
								(SELECT ITH_SER FROM v_ith_tblc WHERE  ITH_FORM NOT IN ('SASTART','SA') AND ITH_DATEC<=@cutoff AND ITH_WH IN (@wh) GROUP BY ITH_SER
									HAVING SUM(ITH_QTY)>0 ) VBEFFG
								LEFT JOIN SER_TBL ON ITH_SER=SER_ID
								WHERE isnull(SER_RMUSE_COMFG,'')!='flg_ok'
								) 


	GROUP BY PIS3_WONO
		,PIS3_MPART,SIMQT,PIS3_DOCNO
) VRESUME_PIS
GROUP BY PIS3_WONO) VRESUME_PISREQ_JOB ON JOB=PIS3_WONO
LEFT JOIN SER_TBL ON SERD2_SER=SER_ID
WHERE TTLPER<TTLPERREQ AND isnull(SER_RMUSE_COMFG,'')!='flg_ok'