declare @wh varchar(20)
set @wh = 'AFWH3'
--DOES SUB ASSY HAVE CALCUALTION 
--SELECT ITH_SER,SER_DOC,SER_QTY FROM
--	(SELECT SERML_COMID ITH_SER
--            FROM (
--                SELECT ITH_SER
--                    ,SUM(ITH_QTY) BEFQTYFG
--                    ,ITH_WH
					
--                FROM v_ith_tblc
--                WHERE ITH_FORM NOT IN (
--                        'SASTART'
--                        ,'SA'
--                        )
--                    AND ITH_DATEC <= '2021-09-26'
--                    AND ITH_WH IN (@wh)
--                GROUP BY ITH_WH
--                    ,ITH_SER
--                HAVING SUM(ITH_QTY) > 0
--                ) VBEFFG
--            INNER JOIN SERML_TBL ON ITH_SER = SERML_NEWID 
--	) VBEFFG
--LEFT JOIN SER_TBL ON ITH_SER=SER_ID
--LEFT JOIN (SELECT DISTINCT SERD2_SER FROM SERD2_TBL ) VSERD2
--ON ITH_SER=SERD2_SER
--WHERE SERD2_SER IS NULL AND SER_QTY >0
--ORDER BY SER_DOC
----IS SUB ASSY CALCULATION OK
--SELECT VRESUME_PER_JOB.*, TTLPERREQ FROM 
--(SELECT SERD2_SER,JOB,SUM(PER) TTLPER FROM
--(SELECT SERD2_SER,SERD2_ITMCD,SUM(SERD2_QTY)/MAX(SERD2_FGQTY) PER, MAX(SERD2_JOB) JOB FROM SERD2_TBL WHERE SERD2_SER IN (
--SELECT SERML_COMID
--            FROM (
--                SELECT ITH_SER
--                    ,SUM(ITH_QTY) BEFQTYFG
--                    ,ITH_WH
					
--                FROM v_ith_tblc
--                WHERE ITH_FORM NOT IN (
--                        'SASTART'
--                        ,'SA'
--                        )
--                    AND ITH_DATEC <= '2021-09-26'
--                    AND ITH_WH IN (@wh)
--                GROUP BY ITH_WH
--                    ,ITH_SER
--                HAVING SUM(ITH_QTY) > 0
--                ) VBEFFG
--            INNER JOIN SERML_TBL ON ITH_SER = SERML_NEWID 
--)
--GROUP BY SERD2_SER ,SERD2_ITMCD) VRESUME_PER_ITEM
--GROUP BY SERD2_SER,JOB) VRESUME_PER_JOB
--LEFT JOIN
--(
--SELECT PIS3_WONO,SUM(REQPER) TTLPERREQ FROM
--	(SELECT PIS3_WONO,PIS3_MPART,SUM(PIS3_REQQT)/SIMQT REQPER FROM XPIS3 
--		RIGHT JOIN ( SELECT PPSN1_WONO,MAX(PPSN1_SIMQT) SIMQT,PPSN1_DOCNO FROM XPPSN1 GROUP BY PPSN1_WONO,PPSN1_DOCNO) VRESUME_PSN1 ON PIS3_WONO=PPSN1_WONO AND PIS3_DOCNO=PPSN1_DOCNO
--		WHERE PIS3_WONO IN (SELECT SER_DOC FROM
--								(SELECT SERML_COMID
--									FROM (
--										SELECT ITH_SER
--											,SUM(ITH_QTY) BEFQTYFG
--											,ITH_WH
--										FROM v_ith_tblc
--										WHERE ITH_FORM NOT IN (
--												'SASTART'
--												,'SA'
--												)
--											AND ITH_DATEC <= '2021-09-26'
--											AND ITH_WH IN (@wh)
--										GROUP BY ITH_WH
--											,ITH_SER
--										HAVING SUM(ITH_QTY) > 0
--									) VBEFFG
--									INNER JOIN SERML_TBL ON ITH_SER = SERML_NEWID 
--								) VBEFFG2
--								LEFT JOIN SER_TBL ON SERML_COMID=SER_ID
--							) 
--	GROUP BY PIS3_WONO
--		,PIS3_MPART,SIMQT,PIS3_DOCNO
--) VRESUME_PIS
--GROUP BY PIS3_WONO) VRESUME_PISREQ_JOB ON JOB=PIS3_WONO
--LEFT JOIN SER_TBL ON SERD2_SER=SER_ID
--WHERE TTLPER<TTLPERREQ AND isnull(SER_RMUSE_COMFG,'')!='flg_ok' --AND (TTLPERREQ-TTLPER)>=1 
--ORDER BY JOB

--select SERML_NEWID,M.SER_QTY MQT,M.SER_DOC MJOB, SERML_COMID,C.SER_QTY CQT, C.SER_DOC CJOB from SERML_TBL 
--left join SER_TBL M ON SERML_NEWID=M.SER_ID 
--LEFT JOIN SER_TBL C ON SERML_COMID=C.SER_ID
--where SERML_NEWID in
--(
--'G1OTE13NDCIX3KJ3',
--'G1OTE13ND8IXMC3P',
--'G1OTE13NDDIX2O17',
--'G1OTE13ND5IX2OJR',
--'G1OTE13NDAIX9SYN'
--) order by SERML_NEWID


--SELECT VBEFFG.*
--                ,SERML_COMID
--            FROM (
--                SELECT ITH_SER
--                    ,SUM(ITH_QTY) BEFQTYFG
--                    ,ITH_WH
--                FROM v_ith_tblc
--                WHERE ITH_FORM NOT IN (
--                        'SASTART'
--                        ,'SA'
--                        )
--                    AND ITH_DATEC <= '2021-09-26'
--                    AND ITH_WH IN (
--                        'AFWH3'
--                        ,'QAFG'
--                        ,'AFWH9SC'
--                        ,'AWIP1'
--                        ,'ARSHP'
--                        )
--                GROUP BY ITH_WH
--                    ,ITH_SER
--                HAVING SUM(ITH_QTY) > 0
--                ) VBEFFG
--            INNER JOIN SERML_TBL ON ITH_SER = SERML_NEWID