<div style="padding: 10px">
	<div class="container-fluid">
        <div class="row">
            <div class="col-md-4 mb-1">
                <div class="input-group input-group-sm">
                    <label class="input-group-text">Internal Code</label>
                    <input type="text" class="form-control" id="itmreg_txtitmcd" readonly>                    
                </div>
            </div>
            <div class="col-md-4 mb-1">
                <div class="input-group input-group-sm">
                    <label class="input-group-text">Item Name</label>
                    <input type="text" class="form-control" id="itmreg_txtitmnm1">
                </div>
            </div>
            <div class="col-md-4 mb-1">
                <div class="input-group input-group-sm">
                    <label class="input-group-text">External Code</label>
                    <input type="text" class="form-control" id="itmreg_txtitmcd_ext">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 mb-1">
                <div class="input-group input-group-sm">                    
                    <label class="input-group-text">Unit Measurement</label>
                    <select class="form-select" id="itmreg_cmbunitmeasure">
                        <?=$UMl?>
                    </select>
                </div>
            </div>
            <div class="col-md-6 mb-1">
                <div class="input-group input-group-sm">                             
                    <span class="input-group-text">Initial</span>
                    <select id="itmreg_consignee"	class="form-select">
                        <option value="-">-</option>
                        <?php
                        foreach($ldeliverycode as $r){
                            ?>
                            <option value="<?=trim($r->MDEL_DELCD)?>"><?=$r->MDEL_DELCD?></option>
                            <?php
                        }
                        ?> 
                    </select>      
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 mb-1">
                <div class="btn-group btn-group-sm">
                    <button title="New" id="itmreg_btnnew" onclick="itmreg_btnnew_eCK()" class="btn btn-primary" ><i class="fas fa-file"></i></button>
                    <button title="Save" id="itmreg_btnsave" class="btn btn-primary" onclick="itmreg_btnsave_eCK()" ><i class="fas fa-save"></i></button>                    
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    var itemreg_isnew = false
    function itmreg_btnsave_eCK(){
        const itmcd = document.getElementById('itmreg_txtitmcd').value
        const itmcd_ext = document.getElementById('itmreg_txtitmcd_ext').value
        const itmnm = document.getElementById('itmreg_txtitmnm1').value        
        const itmunitmeasure = document.getElementById('itmreg_cmbunitmeasure').value
        const itmconsignee = document.getElementById('itmreg_consignee').value
        if(itmnm.trim().length==0){
            alertify.warning('item name could not be empty')
            return
        }
        if(itemreg_isnew && itmcd.length==0){
            if(itmconsignee=='-'){
                alertify.warning('initial code could not be empty')
                return
            }
            if(!confirm("Internal Code will be generated by system with initial code '"+itmconsignee+"', are you sure ?")){
                return
            }
        }

        if(confirm("Are you sure ?")) {
            $.ajax({
                type: "POST",
                url: "<?=base_url('MSTITM/register')?>",
                data: {itmcd: itmcd, itmnm: itmnm,  itmunitmeasure: itmunitmeasure, itmconsignee: itmconsignee, itemreg_isnew: itemreg_isnew, 
                    itmcd_ext: itmcd_ext},
                dataType: "JSON",
                success: function (response) {
                    if(response.status[0].cd=='1'){
                        alertify.success(response.status[0].msg)
                        document.getElementById('itmreg_txtitmcd').value = response.status[0].newcd
                    } else {
                        alertify.message(response.status[0].msg)
                    }
                }, error: function(xhr, xopt, xthrow){
                    alertify.error(xthrow);
                }
            })
        }
    }

    function itmreg_btnnew_eCK(){
        itemreg_isnew = true
        const txtitmcd = document.getElementById('itmreg_txtitmcd')
        const txtitmnm = document.getElementById('itmreg_txtitmnm1')
        const txtitmcd_Ext = document.getElementById('itmreg_txtitmcd_ext')
        txtitmcd.readOnly = false
        txtitmcd.focus()
        txtitmcd.value = ''
        txtitmnm.value = ''
        txtitmcd_Ext.value = ''
    }
</script>